name: Build versions.json

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 * * *

# env:
#   aws_region: eu-west-2
#   s3_bucket: julialang2

jobs:
  build-json-map:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'

        - name: Check if there was a Julia release within the last week
          id: rebuild-check
          run: julia --color=yes --project rebuild_check.jl
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create version map
          if: steps.rebuild-check.outputs.rebuild == 'true'
          run: julia --color=yes --project build_json_map.jl versions.json
        
        # Upload version.json as workflow artifact for debugging purposes
        - uses: actions/upload-artifact@v2
          if: steps.rebuild-check.outputs.rebuild == 'true'
          with:
            name: versions
            path: versions.json
            if-no-files-found: error

        # - name: Configure AWS credentials
        #   uses: aws-actions/configure-aws-credentials@v1
        #   if: steps.rebuild-check.outputs.rebuild == 'true'
        #   with:
        #     aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
        #     aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
        #     aws-region: ${{ env.aws_region }}
          
        # - name: Upload versions.json to s3
        #   if: steps.rebuild-check.outputs.rebuild == 'true'
        #   run: |
        #     aws s3 sync versions.json s3://${{ env.s3_bucket }}/bin/versions.json --acl public-read --no-progress
